namespace VideoEnhancer;

internal sealed class ServiceOptions
{

        public bool ShowHelp;
        public bool ShowVersion;
        public bool ListModels;
        public bool ListModelCatalog;
        public bool ListInterpModelCatalog;
        public bool ListUserModels;
        public bool CheckOnly;
        public bool DebugSplit;
        public bool Json;
        public string Input = "";
        public bool HasInput;
        public string Model = "";
        public bool HasModel;
        public string FfmpegSettings = "";
        public bool HasFfmpegSettings;
        public string FfmpegPath = "";
        public string FfprobePath = "";
        public string OutputScale = "";
        public string ScaleOverride = "";
        public bool HasScaleOverride;
        public string PauseShm = "";
        public bool HasPauseShm;
        public string StopShm = "";
        public bool HasStopShm;
        public string InterpModel = "";
        public bool HasInterpModel;
        public string InterpFactor = "";
        public bool HasInterpFactor;
        public bool NoUpscale;
        public bool RtxHdr;
        public string RtxTarget = "2x";
        public string RtxQuality = "3";
        public string RtxHdrContrast = "100";
        public string RtxHdrSaturation = "100";
        public string RtxHdrMiddleGray = "44";
        public string RtxHdrMaxLuminance = "1000";
        public string SegmentsBase64 = "";
        public bool AllowMixedSegmentBackends;
        public bool ListInterpModels;
        public string Backend = "ncnn";
        public bool HasBackend;
        public string InterpBackend = "";
        public bool HasInterpBackend;
        public string ProcessOrder = "upscale-first";
        public string UpscalePrecision = "auto";
        public string InterpPrecision = "auto";
        public string SceneThreshold = "4.0";
        public bool HasSceneThreshold;
        public bool DynamicOpticalFlow;
        public string TileSize = "0";
        public bool HasTileSize;
        public bool ListBackends;
        public bool ValidateEngines;
        public string InspectInterpModel = "";
        public string InspectUpscaleModel = "";
        public string ImportModel = "";
        public string UpdateUserModel = "";
        public string DeleteUserModel = "";
        public string UserArchitecture = "";
        public string UserPurpose = "";
        public string UserScale = "";
        public string UserInputMultiple = "";
        public string UserBackends = "";
        public string PrepareInterpEngine = "";
        public string PrepareWidth = "1920";
        public string PrepareHeight = "1080";
        public bool PrepareStaticShape;
        public bool ListDownloadModels;
        public bool CleanDownloadArchives;
        public string DownloadModel = "";
        public string DeleteDownloadModel = "";
        public bool BackendStatus;
        public bool UpdateBackend;
        public bool ForceBackendFull;
        public string ApplyBackendPatch = "";
        public string BackendChannel = "";
        public string DownloadUrl = "";
        public string DownloadOutput = "";
        public string ExtractArchive = "";
        public string ExtractOutput = "";        public readonly List<string> ImageInputs = new();
        public readonly List<string> ImageFolders = new();
        public string ImageOutput = "";
        public bool ImageOutputOriginal;
        public string ImageSuffix = "timestamp";
        public bool ImagePng = true;
    }
